### ISSUE TITLE
Doesn´t works after reload

### ISSUE THREAD

**Issue by Mencoreh** [Vecnavium/VecnaLeaderboards#24]
08:30:38 Server|INFO > Enabling VecnaLeaderboards v1.2.0
08:30:38 Server|CRITICAL > TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putLFloat() must be of the type float, string given, called in phar:///home/container/PocketMine-MP.phar/src/pocketmine/network/mcpe/NetworkBinaryStream.php on line 658" (EXCEPTION) in "pmsrc/vendor/pocketmine/binaryutils/src/BinaryStream" at line 250
08:30:38 Server|CRITICAL > #0 pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream(658): pocketmine\utils\BinaryStream->putLFloat(string[5] -5.67)
08:30:38 Server|CRITICAL > #1 pmsrc/src/pocketmine/network/mcpe/protocol/AddPlayerPacket(127): pocketmine\network\mcpe\NetworkBinaryStream->putVector3(object pocketmine\math\Vector3)
08:30:38 Server|CRITICAL > #2 pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket(127): pocketmine\network\mcpe\protocol\AddPlayerPacket->encodePayload()
08:30:38 Server|CRITICAL > #3 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(244): pocketmine\network\mcpe\protocol\DataPacket->encode()
08:30:38 Server|CRITICAL > #4 pmsrc/src/pocketmine/Player(3603): pocketmine\network\mcpe\RakLibInterface->putPacket(object pocketmine\Player, object pocketmine\network\mcpe\protocol\AddPlayerPacket, boolean , boolean )
08:30:38 Server|CRITICAL > #5 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecxLeaderboards/Util/CustomFloatingText(65): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\AddPlayerPacket)
08:30:38 Server|CRITICAL > #6 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecxLeaderboards/Leaderboard/Leaderboard(78): Vecnavium\VecxLeaderboards\Util\CustomFloatingText->spawn(object pocketmine\Player)
08:30:38 Server|CRITICAL > #7 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecxLeaderboards/Leaderboard/LeaderboardManager(47): Vecnavium\VecxLeaderboards\Leaderboard\Leaderboard->spawn()
08:30:38 Server|CRITICAL > #8 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecxLeaderboards/Leaderboard/LeaderboardManager(40): Vecnavium\VecxLeaderboards\Leaderboard\LeaderboardManager->registerLeaderboard(integer 214, string[5] kills, object pocketmine\level\Position)
08:30:38 Server|CRITICAL > #9 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecxLeaderboards/Leaderboard/LeaderboardManager(31): Vecnavium\VecxLeaderboards\Leaderboard\LeaderboardManager->loadLeaderboards()
08:30:38 Server|CRITICAL > #10 plugins/VecnaLeaderboards.phar/src/Vecnavium/VecxLeaderboards/Main(49): Vecnavium\VecxLeaderboards\Leaderboard\LeaderboardManager->__construct(object Vecnavium\VecxLeaderboards\Main)
08:30:38 Server|CRITICAL > #11 pmsrc/src/pocketmine/plugin/PluginBase(116): Vecnavium\VecxLeaderboards\Main->onEnable()
08:30:38 Server|CRITICAL > #12 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
08:30:38 Server|CRITICAL > #13 pmsrc/src/pocketmine/Server(1896): pocketmine\plugin\PluginManager->enablePlugin(object Vecnavium\VecxLeaderboards\Main)
08:30:38 Server|CRITICAL > #14 pmsrc/src/pocketmine/Server(1882): pocketmine\Server->enablePlugin(object Vecnavium\VecxLeaderboards\Main)
08:30:38 Server|CRITICAL > #15 pmsrc/src/pocketmine/Server(1973): pocketmine\Server->enablePlugins(integer 1)
08:30:38 Server|CRITICAL > #16 pmsrc/src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()
08:30:38 Server|CRITICAL > #17 pmsrc/src/pocketmine/command/SimpleCommandMap(263): pocketmine\command\defaults\ReloadCommand->execute(object pocketmine\Player, string[6] reload, array[0])
08:30:38 Server|CRITICAL > #18 pmsrc/src/pocketmine/Server(1920): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[6] reload)
08:30:38 Server|CRITICAL > #19 pmsrc/src/pocketmine/Player(3459): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[6] reload)
08:30:38 Server|CRITICAL > #20 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(287): pocketmine\Player->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08:30:38 Server|CRITICAL > #21 pmsrc/src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08:30:38 Server|CRITICAL > #22 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08:30:38 Server|CRITICAL > #23 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(133): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08:30:38 Server|CRITICAL > #24 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08:30:38 Server|CRITICAL > #25 pmsrc/src/pocketmine/Player(3555): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08:30:38 Server|CRITICAL > #26 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08:30:38 Server|CRITICAL > #27 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 190.84.119.144 5218, object raklib\protocol\EncapsulatedPacket, integer 0)
08:30:38 Server|CRITICAL > #28 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
08:30:38 Server|CRITICAL > #29 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
08:30:38 Server|CRITICAL > #30 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
08:30:38 Server|CRITICAL > #31 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
08:30:38 Server|CRITICAL > #32 pmsrc/src/pocketmine/Server(2265): pocketmine\snooze\SleeperHandler->sleepUntil(double 1624696236.8301)
08:30:38 Server|CRITICAL > #33 pmsrc/src/pocketmine/Server(2105): pocketmine\Server->tickProcessor()
08:30:38 Server|CRITICAL > #34 pmsrc/src/pocketmine/Server(1689): pocketmine\Server->start()
08:30:38 Server|CRITICAL > #35 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
08:30:38 Server|CRITICAL > #36 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
08:30:38 Server|CRITICAL > #37 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
08:30:38 Server|INFO > Disabling VecnaLeaderboards v1.2.0
08:30:38 Server|CRITICAL > Error: "Call to a member function saveLeaderboards() on null" (EXCEPTION) in "plugins/VecnaLeaderboards.phar/src/Vecnavium/VecxLeaderboards/Main" at line 61
08:30:38 Server|CRITICAL > #0 pmsrc/src/pocketmine/plugin/PluginBase(118): Vecnavium\VecxLeaderboards\Main->onDisable()
08:30:38 Server|CRITICAL > #1 pmsrc/src/pocketmine/plugin/PluginManager(639): pocketmine\plugin\PluginBase->setEnabled(boolean )
08:30:38 Server|CRITICAL > #2 pmsrc/src/pocketmine/plugin/PluginManager(559): pocketmine\plugin\PluginManager->disablePlugin(object Vecnavium\VecxLeaderboards\Main)
08:30:38 Server|CRITICAL > #3 pmsrc/src/pocketmine/Server(1896): pocketmine\plugin\PluginManager->enablePlugin(object Vecnavium\VecxLeaderboards\Main)
08:30:38 Server|CRITICAL > #4 pmsrc/src/pocketmine/Server(1882): pocketmine\Server->enablePlugin(object Vecnavium\VecxLeaderboards\Main)
08:30:38 Server|CRITICAL > #5 pmsrc/src/pocketmine/Server(1973): pocketmine\Server->enablePlugins(integer 1)
08:30:38 Server|CRITICAL > #6 pmsrc/src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()
08:30:38 Server|CRITICAL > #7 pmsrc/src/pocketmine/command/SimpleCommandMap(263): pocketmine\command\defaults\ReloadCommand->execute(object pocketmine\Player, string[6] reload, array[0])
08:30:38 Server|CRITICAL > #8 pmsrc/src/pocketmine/Server(1920): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[6] reload)
08:30:38 Server|CRITICAL > #9 pmsrc/src/pocketmine/Player(3459): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[6] reload)
08:30:38 Server|CRITICAL > #10 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(287): pocketmine\Player->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08:30:38 Server|CRITICAL > #11 pmsrc/src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08:30:38 Server|CRITICAL > #12 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08:30:38 Server|CRITICAL > #13 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(133): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
08:30:38 Server|CRITICAL > #14 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(126): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
08:30:38 Server|CRITICAL > #15 pmsrc/src/pocketmine/Player(3555): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08:30:38 Server|CRITICAL > #16 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
08:30:38 Server|CRITICAL > #17 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[19] 190.84.119.144 5218, object raklib\protocol\EncapsulatedPacket, integer 0)
08:30:38 Server|CRITICAL > #18 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
08:30:38 Server|CRITICAL > #19 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
08:30:38 Server|CRITICAL > #20 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
08:30:38 Server|CRITICAL > #21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
08:30:38 Server|CRITICAL > #22 pmsrc/src/pocketmine/Server(2265): pocketmine\snooze\SleeperHandler->sleepUntil(double 1624696236.8301)
08:30:38 Server|CRITICAL > #23 pmsrc/src/pocketmine/Server(2105): pocketmine\Server->tickProcessor()
08:30:38 Server|CRITICAL > #24 pmsrc/src/pocketmine/Server(1689): pocketmine\Server->start()
08:30:38 Server|CRITICAL > #25 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
08:30:38 Server|CRITICAL > #26 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
08:30:38 Server|CRITICAL > #27 pmsrc(11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by Vecnavium** [comment]
Hi, first off please do not use spoons/forks of PocketMine-MP and use the original default build/version if you are trying to get help with an issue of this plugin. 
Secondly, it's highly recommended to not use /reload as it does break some plugins so please if you can avoid using /reload. PM4 will be having /reload removed if I recall so theres no point on trying to have a code that evades this issue.

**Comment by Vecnavium** [comment]
Issue has been resolved via Discord with the user
