### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by deadbushmc** [Vecnavium/VecnaLeaderboards#27]
I killed a guy and my kills went from 1 to 12 lmao same with other things please fix em

**Comment by Vecnavium** [comment]
Hi, are you using the full source of the plugin from https://poggit.pmmp.io/p/VecnaLeaderboards ? As this bug you have mentioned is not occurring to me as I have reproduced it by killing a dummy twice and it's counting up by one, I already had a feeling this bug report wasn't an actual bug from the start. So please be sure you are using the plugin directly from https://poggit.pmmp.io/p/VecnaLeaderboards and without modifications of sorts and I can guarantee you that you will not face any problems as I tested this with the latest version and I had no problems.
