### ISSUE TITLE
Create a user with lowercase letters and do not level up the leaderboard

### ISSUE THREAD

**Issue by MrBlasyMSK** [Vecnavium/VecnaLeaderboards#29]
**Describe the bug**
He has created 2 users with the same name and does not put the experience points that I have

**To Reproduce**
Put a leaderboard of levels
Get experience
Bug

**Expected behavior**
A clear and concise description of what you expected to happen: That it will count the user experience and that it will not create another user with the names in lowercase
**VecnaLeaderboards plugin information**

- Plugin Version: Dev272

**Screenshots**
![image](https://user-images.githubusercontent.com/85447029/129710369-201825f2-7af3-4ca3-bf94-e18701d65752.png)

**Additional context**

**Comment by Vecnavium** [comment]
Levels leaderboard isn't based on EXP its based on kills which also relates to levels.  If you check the config.yml you will see the levels system on the very bottom of the config, thats what the levels leaderboard is tracking not EXP

**Comment by MrBlasyMSK** [comment]
Ohhh I understand I understand, but why has another nickname been created but in lowercase?

**Comment by MrBlasyMSK** [comment]
Could it be by using a command like / give mrblasymsk 1?

**Comment by Vecnavium** [comment]
Well did that happen after you ran the give command or it was always there?

**Comment by MrBlasyMSK** [comment]
I just used the / give mrblasymsk 1 and it was added to the list

**Comment by Vecnavium** [comment]
I have tried to reproduce the issue you are having and this issue isn't happening to me, only plugins I had installed was EconomyAPI, Specter (didnt use specter to test this), DevTools and VecnaLeaderboards

**Comment by MrBlasyMSK** [comment]
Well it is not a very important error, I close the issue
