### ISSUE TITLE
New leaderboards

### ISSUE THREAD

**Issue by MrBlasyMSK** [Vecnavium/VecnaLeaderboards#30]
- [ ] Top players who have entered the server the most times
- [ ] Top players with the most number of blocks placed
- [ ] Top players with the most number of broken blocks
- [ ] Top players with the most server jumps
- [ ] Top players with the most messages sent from the server
- [ ] Top players who have crafted the most
- [ ] Top players who have consumed the most objects (food, potions, etc.)
- [ ] Top players with the highest server EXP
- [ ] Top most active players (timer)
- [ ] Top players with the most blocks traveled

**Comment by Vecnavium** [comment]
I am not sure if all those features will be implemented as they are sort of irrelevant and chances of destroying server performance caused by this plugin if we/I add all these features due to the amount of tasks and data that'll be stored all at once.

**Comment by Vecnavium** [comment]
Please refer to issue #36 and my response above remains the same.
