### ISSUE TITLE
Pls Fix It

### ISSUE THREAD

**Issue by rokibot009** [Vecnavium/VecnaLeaderboards#33]
![Screenshot_20210831_025136_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/74145332/131397979-4752a709-e154-43e4-8233-f963446435ff.jpg)

Pls Fix it

**Comment by rokibot009** [comment]
Duplicate name at leaderboards

**Comment by MrNinja008** [comment]
I can confirm this it happened me to one was uppercase and one was lowe case like it says MrNinja008 and mrninja008

**Comment by Vecnavium** [comment]
Seems like an issue exactly like https://github.com/Vecnavium/VecnaLeaderboards/issues/29. I will be closing this and please refer to issue 29 which is the link I sent here.
