### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by LittleCutePM** [Vecnavium/VecnaLeaderboards#36]
Can you add top played time?

**Comment by Vecnavium** [comment]
I do not think I will be doing anymore features to be added to the plugin and feature freeze it for only PM3 (API 3.0.0)
As PM4(API4.0.0) is in beta PM3 will eventually not too long from now will not be the main version and PM4 will be the main version. Only adding new features to this plugin for PM4 of VecnaLeaderboards. 

And for me to add top played time I would need a plugin made such as OnlineTime or something like that but in PM4 as I do not  plan on doing some plugin that tracks played time nor implement it as a feature like that within the plugin and use it's API if there is a PM4 plugin for that.
